apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-ml-deployment-rolling-update
  labels:
    app: fastapi-ml-deployment-rolling-update
spec:
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: fastapi-ml
  template:
    metadata:
      name: fastapi-ml
      labels:
        app: fastapi-ml
    spec:
      containers:
        - image: aweesomesse/ml_prod_homework2:v2
          name: fastapi-ml
          ports:
            - containerPort: 8000