apiVersion: v1
kind: Pod
metadata:
  name: fastapi-ml-pod-resources
  labels:
    app: fastapi-ml-pod-resources
spec:
  containers:
    - image: aweesomesse/ml_prod_homework2:v1
      name: fastapi-ml
      ports:
        - containerPort: 8000
      resources:
        requests:
            memory: "100Mi"
            cpu: 1
        limits:
            memory: "200Mi"
            cpu: 2